server:
  port: 8150 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  redis:
    host: 192.168.80.128
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

#阿里云短信
aliyun:
  sms:
    regionId: cn-beijing
    keyId: LTAI4Fpb7bZepit9DSAAhc3V
    keySecret: h3rDvtprh5dDu3qZ2o0kLOGkNCzHtY
    templateCode: SMS_96695065
    signName: 谷粒